language: scala
scala: 2.12.9
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "fepvbR5QfdxNF/3jkGAChyZJ03dHEdLCzPZ/eTUbFIVZ/kMpSaYpaBGig70W7aGOXav97af1/xdQs14Vqya/4LeBvELZuheDxBerSHGw7+uMlkCm7Cw159OP29hYEzOLtxrdVW0duhetgSXn/o4JyZoZyZeDpJhg4H0sy+8wC7/zHiYA5yJnxUHlfq+ibyTSMzWhjXj7K1HcId079DYyVGwGDVQpPrpNzCwy+t2QKTvo52J7JPSX6x9k7SBr/yHMU2AK3jyQJ8M5oiD9OTTn0dhm47qNNRTjkuFVqZBCe+Igtg8/IKhpppnnrhv3+c1kEPFuHSOCmXnWYSWMsEJkMX33bQCSpHu0PwXGOcv7zUUi49P6vnP+rt1C0WGT45xJnxuQo9MJ3/rZq3NjhW81t4jcx/ZZFb6te+vcS34etXuGCE4vUbjnmESgcOLEAmZMT9D8Iea2YHSmldJLtIVlTz0CbN6JAVd4VT5njkEctzYUp/omVGLAIvhRfWFRhxfjSxUqlK8qCLCyqjBAiv6pI2OO724PnMCZQTafn/mEvITysnHNbznv173SVuUlIfZ5dXGjWhlBza17BeuzpdTpaH+zA8s73lIMPM6sbvAQIVYQRrPzMR+tC4tRpWp2RVglpIJBozxBpoicvtEAm7so4xNt6ev+FKORf8NxSyiW8gc="
    # GITHUB_TOKEN
    - secure: "eMd5rFrDfEeEoU71L+J4ph7jDzMhpkHA3PIn/3w9lcLXRcBn3C3B24jx2Gl3jbKvShO0UAWjXL/UFIxUQOxUFow2x/bWXHOvS4qdZDXaPea8OwsSkfM/IxUfQdEJNtp2Q/Zp9+a0+b5l6TTy/HNKTFdrNt0/mv+PLHbc855pEQZoy2FGFroTZ3VqrBaHNYqFnbA18qrFN9tVYeDoD+Wp/UGnWacko3TB76vAR05W7QiuN2gVhG5F4aokNLbZ1oWSIQeAVwwhc+GVDSsdQ5djzohZsNHjSXUgdO2ZJkXE/LfyGFD/oGcgzvC5+k5kOdiEKDv8L2ZQ54x37IF4FLvm2tQw9nZ0Me9GjRqUbNIdfulFH7ogANhXNjYZYpBta6L63ZS6Sprk2bjUQQxqt1iae2TnEuR2e1SEqKGYlUK2lUgjijRqpfubER/8FoFWu2nVKFdYzONhm1w/IHuIsY+QxBZqjn4NPhSL3O7OXkhcZOYRhB9y/423GbEQcPkAfrcPMKVSdUyre0K+0+TERlUnFosqH9fR+mbb5zrFpUeakTfXOABv736/ZEMTv+hhE1nb+GPb3bpfAnoo+DB3SagsODanaTWSoxIBb8+CxiKo2IZ8DdUd0UHyPyxtTcrKpvUZtAk4k3FbSB8iau0UVSlgbt6/yPcy/AbBm8CXvQ4gvJc="
    # GITHUB_ACCESS_TOKEN
    - secure: "iJuo7b6pzDgrTWd/RMM3dAnX9W7jxH/HlWdv86co+EjdtrAl1f4Ezp3GFpkQWdyglL5vh88nfU/DTUR592xJEh+pcryQu/GhHsdFtlk/lY4DjcEU1jepy7JcuScBbWB7maxeMveXr9JqZp/tIcWW3Mpdvv45+s5KS2h/38P/tpfcQ4TXTq8FADKjksWEox+swXrYJKCgm7RnuX4R/ubvK9zwu6Y44qhya2NZpQ3Hz5BX6nqVWXQmTmnCy9cdAe07STVBNjQnUyCDtucUyAiDfykjsj0f6PGRDj37OfTw29BLFUN+7TUVKEofjzPigxBOQDij/IfdMOrqPiybW/Yt0ZT2l9+ujR5v3de9sij1lyPmimO14ux8/5xcmyiLSdGD/LHQB081L9IeRgOg5atuElHxQ674Hxzns77D5U7dFL6/vtJxeqZ9IsB4B5V/CRXuCJ+LoP5JF5lf8+cLfFBiQ7b04a3MbxTj15qiJoKj/ShSPkWDipC+Ey1lQAQdDC9tQMHo/7gPvYpNCWhewwejVJkTxU6X7dk9pSpmmuRjecm/IhNhyzU6QcoRx79YCX9smJtvtBXXHfkowOSRu9qjleHlTcb0Zmm7I+ANBNSVW2N2l4nNtDDF9OK2A2M5N7/E2Y8N7A6hXo3B8MGzSCc4ji2XFtq4DCaAvonCx5VwG9A="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "FqX3vYI8ui/dkujMVL4/vbZfu78kOcZf2v7ZhQyG5pILohB8NxcUAfc1g+aJZFwom4fH1ebKrbyE5tDDXgwyuN1oIUVG3GdNeRt72tdhOQf+gKuoeC096p3imJjghcNinWezXIZHAxYa9Zaw5Y06bLJaaV1BTi4TZbOJsdwgKbzr7Wg6pNL7MR3gsJaQb2GbIotvUCTq713TfctrEyQdX6AsTPxBrvt2xtddSLo9WhiID4H882ay+WgGcbmmBBxKr+U/p1LoMWSQ7CU6fWacBt0ki3llfjOxGw2lMYFBMcOcnxm60qPfk/uhcrjU5Jr8XgZ17z2OeQse538muKeWmaeg4LitOSXFudmjL0V9fsattgnqLh7LC7y9jbQpQQ+CAQmF/kkIRpfD/3u6FNzI7WnWWVn6TRVyhrkiUunv2ofoeuzi8KL7/OKCyY65Bslk/O0WeN2W8M8mEvFpJ95z8gu/JD6cfIVUSU6innnq+LbGhJZxy+dlz+UUzNm48mO3n3CEA8TbM2I4FE4QS7gXm6JRvQtdhZhYrL0IQOZ4+03oBUX5BrZ2+g0YFXsh0My8inex4QJGfh9gtL2gFdmjbp0p6TIDvzPMVS9p0qycZ5QLlJX05xqMVwJPubnE7ZurWb7W2WghV/zCJwdxvIM+mkQ4WIRLmjXSWE+ZsXPizfU="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/sbt-quasar-destination';
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
